### DISCUSSION TITLE
How to deploy your stories app based on Blazor WebAssembly to GitHub Pages

### DISCUSSION THREAD

**Discussion by jsakamoto** [jsakamoto/BlazingStory#33] [General]
@aglasencnik
> Also, I got the github pages working, but I had to change the base path of both iframe and index with the sed command in actions (you can look in the repo I sent)...

Of course, it must work fine. But in my opinion, it would be better to use the ["PublishSPAforGitHubPages.Build"](https://github.com/jsakamoto/PublishSPAforGitHubPages.Build) NuGet package. 
See also: _["The easier way to publish your Blazor WebAssembly app for GitHub Pages | dev.to"](https://dev.to/j_sakamoto/the-easier-way-to-publish-your-blazor-webassembly-app-for-github-pages-319l)_

For instance, I've used that NuGet package to deploy my sample story app to the GitHub Pages, as shown below.

- https://github.com/jsakamoto/BlazingStory/blob/main/Samples/MyBlazorWasmApp1/MyBlazorWasmApp1.Stories/MyBlazorWasmApp1.Stories.csproj#L16
- https://github.com/jsakamoto/BlazingStory/blob/main/.github/workflows/gh-pages.yml

**Comment by AlexHedley** [comment]
An alternative, update `REPO_NAME` to your repo name:

```yml
      # changes the base-tag in index.html from '/' to 'REPO_NAME' to match GitHub Pages repository subdirectory
      - name: ✏ Change base-tag in index.html from / to REPO_NAME
        run: sed -i 's/<base href="\/" \/>/<base href="\/REPO_NAME\/" \/>/g' public/wwwroot/index.html

      - name: ✏ Change base-tag in iframe.html from / to REPO_NAME
        run: sed -i 's/<base href="\/" \/>/<base href="\/REPO_NAME\/" \/>/g' public/wwwroot/iframe.html

      # copy index.html to 404.html to serve the same file when a file is not found
      - name: 🗐 copy index.html to 404.html
        run: cp public/wwwroot/index.html public/wwwroot/404.html
  
      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: ➕ Add .nojekyll file
        run: touch public/wwwroot/.nojekyll
```
